version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: "daily"
  open-pull-requests-limit: 10
  groups:
    cdk-libs:
      patterns:
        - "aws-cdk*"
        - "constructs"
    boto-libs:
      patterns:
        - "boto*"
  ignore:
  - dependency-name: "boto*"
    update-types: ["version-update:semver-patch"]
  - dependency-name: "django"
    versions:
      # We don't want notifications about Django 5
      # until 5.2 LTS is released in 2025
      - ">= 5.0"
