# handy test data we can use to keep the tests terse

base_data = {
    "allerdale": {
        "slug": "allerdale",
        "name": "Allerdale",
        "register_code": None,
        "url": "http://www.lgbce.org.uk/all-reviews/north-west/cumbria/allerdale",
        "status": "Recent Reviews",
        "latest_event": None,
        "shapefiles": None,
        "eco": None,
        "eco_made": 0,
    },
    "ashford": {
        "slug": "ashford",
        "name": "Ashford",
        "register_code": None,
        "url": "http://www.lgbce.org.uk/all-reviews/south-east/kent/ashford",
        "status": "Recent Reviews",
        "latest_event": None,
        "shapefiles": None,
        "eco": None,
        "eco_made": 0,
    },
    "babergh": {
        "slug": "babergh",
        "name": "Babergh",
        "register_code": None,
        "url": "http://www.lgbce.org.uk/all-reviews/eastern/suffolk/babergh",
        "status": "Current Reviews",
        "latest_event": None,
        "shapefiles": None,
        "eco": None,
        "eco_made": 0,
    },
    "basingstoke-and-deane": {
        "slug": "basingstoke-and-deane",
        "name": "Basingstoke and Deane",
        "register_code": None,
        "url": "http://www.lgbce.org.uk/all-reviews/south-east/hampshire/basingstoke-and-deane",
        "status": "Current Reviews",
        "latest_event": None,
        "shapefiles": None,
        "eco": None,
        "eco_made": 0,
    },
}
