# handy test data we can use to keep the tests terse

base_data = {
    "fake_org_1": {
        "slug": "babergh",
        "name": "Babergh",
        "register_code": None,
        "consultation_url": "http://www.lgbce.org.uk/all-reviews/babergh",
        "status": None,
        "latest_event": None,
        "boundaries_url": None,
        "legislation_url": None,
        "legislation_made": 0,
        "legislation_title": None,
    },
    "fake_org_2": {
        "slug": "gateshead",
        "name": "Gateshead",
        "register_code": None,
        "consultation_url": "http://www.lgbce.org.uk/all-reviews/gateshead",
        "status": None,
        "latest_event": None,
        "boundaries_url": None,
        "legislation_url": None,
        "legislation_made": 0,
        "legislation_title": None,
    },
    "allerdale": {
        "slug": "allerdale",
        "name": "Allerdale",
        "register_code": None,
        "consultation_url": "http://www.lgbce.org.uk/all-reviews/allerdale",
        "status": None,
        "latest_event": None,
        "boundaries_url": None,
        "legislation_url": None,
        "legislation_made": 0,
        "legislation_title": None,
    },
    "babergh": {
        "slug": "babergh",
        "name": "Babergh",
        "register_code": None,
        "consultation_url": "http://www.lgbce.org.uk/all-reviews/babergh",
        "status": None,
        "latest_event": None,
        "boundaries_url": None,
        "legislation_url": None,
        "legislation_made": 0,
        "legislation_title": None,
    },
    "calderdale": {
        "slug": "calderdale",
        "name": "Calderdale",
        "register_code": None,
        "consultation_url": "http://www.lgbce.org.uk/all-reviews/calderdale",
        "status": None,
        "latest_event": None,
        "boundaries_url": None,
        "legislation_url": None,
        "legislation_made": 0,
        "legislation_title": None,
    },
    "dacorum": {
        "slug": "dacorum",
        "name": "Dacorum",
        "register_code": None,
        "consultation_url": "http://www.lgbce.org.uk/all-reviews/dacorum",
        "status": None,
        "latest_event": None,
        "boundaries_url": None,
        "legislation_url": None,
        "legislation_made": 0,
        "legislation_title": None,
    },
    "ealing": {
        "slug": "ealing",
        "name": "Ealing",
        "register_code": None,
        "consultation_url": "http://www.lgbce.org.uk/all-reviews/ealing",
        "status": None,
        "latest_event": None,
        "boundaries_url": None,
        "legislation_url": None,
        "legislation_made": 0,
        "legislation_title": None,
    },
    "fareham": {
        "slug": "fareham",
        "name": "Fareham",
        "register_code": None,
        "consultation_url": "http://www.lgbce.org.uk/all-reviews/fareham",
        "status": None,
        "latest_event": None,
        "boundaries_url": None,
        "legislation_url": None,
        "legislation_made": 0,
        "legislation_title": None,
    },
    "gateshead": {
        "slug": "gateshead",
        "name": "Gateshead",
        "register_code": None,
        "consultation_url": "http://www.lgbce.org.uk/all-reviews/gateshead",
        "status": None,
        "latest_event": None,
        "boundaries_url": None,
        "legislation_url": None,
        "legislation_made": 0,
        "legislation_title": None,
    },
    "hackney": {
        "slug": "hackney",
        "name": "Hackney",
        "register_code": None,
        "consultation_url": "http://www.lgbce.org.uk/all-reviews/hackney",
        "status": None,
        "latest_event": None,
        "boundaries_url": None,
        "legislation_url": None,
        "legislation_made": 0,
        "legislation_title": None,
    },
    "ipswich": {
        "slug": "ipswich",
        "name": "Ipswich",
        "register_code": None,
        "consultation_url": "http://www.lgbce.org.uk/all-reviews/ipswich",
        "status": None,
        "latest_event": None,
        "boundaries_url": None,
        "legislation_url": None,
        "legislation_made": 0,
        "legislation_title": None,
    },
    "kensington-and-chelsea": {
        "slug": "kensington-and-chelsea",
        "name": "Kensington and Chelsea",
        "register_code": None,
        "consultation_url": "http://www.lgbce.org.uk/all-reviews/kensington-and-chelsea",
        "status": None,
        "latest_event": None,
        "boundaries_url": None,
        "legislation_url": None,
        "legislation_made": 0,
        "legislation_title": None,
    },
    "lambeth": {
        "slug": "lambeth",
        "name": "Lambeth",
        "register_code": None,
        "consultation_url": "http://www.lgbce.org.uk/all-reviews/lambeth",
        "status": None,
        "latest_event": None,
        "boundaries_url": None,
        "legislation_url": None,
        "legislation_made": 0,
        "legislation_title": None,
    },
    "macclesfield": {
        "slug": "macclesfield",
        "name": "Macclesfield",
        "register_code": None,
        "consultation_url": "http://www.lgbce.org.uk/all-reviews/macclesfield",
        "status": None,
        "latest_event": None,
        "boundaries_url": None,
        "legislation_url": None,
        "legislation_made": 0,
        "legislation_title": None,
    },
    "new-forest": {
        "slug": "new-forest",
        "name": "New Forest",
        "register_code": None,
        "consultation_url": "http://www.lgbce.org.uk/all-reviews/new-forest",
        "status": None,
        "latest_event": None,
        "boundaries_url": None,
        "legislation_url": None,
        "legislation_made": 0,
        "legislation_title": None,
    },
    "oadby-and-wigston": {
        "slug": "oadby-and-wigston",
        "name": "Oadby and Wigston",
        "register_code": None,
        "consultation_url": "http://www.lgbce.org.uk/all-reviews/oadby-and-wigston",
        "status": None,
        "latest_event": None,
        "boundaries_url": None,
        "legislation_url": None,
        "legislation_made": 0,
        "legislation_title": None,
    },
    "pabr-barnsley-and-sheffield": {
        "slug": "pabr-barnsley-and-sheffield",
        "name": "PABR - Barnsley and Sheffield",
        "register_code": None,
        "consultation_url": "http://www.lgbce.org.uk/all-reviews/pabr-barnsley-and-sheffield",
        "status": None,
        "latest_event": None,
        "boundaries_url": None,
        "legislation_url": None,
        "legislation_made": 0,
        "legislation_title": None,
    },
    "reading": {
        "slug": "reading",
        "name": "Reading",
        "register_code": None,
        "consultation_url": "http://www.lgbce.org.uk/all-reviews/reading",
        "status": None,
        "latest_event": None,
        "boundaries_url": None,
        "legislation_url": None,
        "legislation_made": 0,
        "legislation_title": None,
    },
    "salford": {
        "slug": "salford",
        "name": "Salford",
        "register_code": None,
        "consultation_url": "http://www.lgbce.org.uk/all-reviews/salford",
        "status": None,
        "latest_event": None,
        "boundaries_url": None,
        "legislation_url": None,
        "legislation_made": 0,
        "legislation_title": None,
    },
    "tameside": {
        "slug": "tameside",
        "name": "Tameside",
        "register_code": None,
        "consultation_url": "http://www.lgbce.org.uk/all-reviews/tameside",
        "status": None,
        "latest_event": None,
        "boundaries_url": None,
        "legislation_url": None,
        "legislation_made": 0,
        "legislation_title": None,
    },
    "uttlesford": {
        "slug": "uttlesford",
        "name": "Uttlesford",
        "register_code": None,
        "consultation_url": "http://www.lgbce.org.uk/all-reviews/uttlesford",
        "status": None,
        "latest_event": None,
        "boundaries_url": None,
        "legislation_url": None,
        "legislation_made": 0,
        "legislation_title": None,
    },
    "vale-white-horse": {
        "slug": "vale-white-horse",
        "name": "Vale of White Horse",
        "register_code": None,
        "consultation_url": "http://www.lgbce.org.uk/all-reviews/vale-white-horse",
        "status": None,
        "latest_event": None,
        "boundaries_url": None,
        "legislation_url": None,
        "legislation_made": 0,
        "legislation_title": None,
    },
    "wakefield": {
        "slug": "wakefield",
        "name": "Wakefield",
        "register_code": None,
        "consultation_url": "http://www.lgbce.org.uk/all-reviews/wakefield",
        "status": None,
        "latest_event": None,
        "boundaries_url": None,
        "legislation_url": None,
        "legislation_made": 0,
        "legislation_title": None,
    },
    "york": {
        "slug": "york",
        "name": "York",
        "register_code": None,
        "consultation_url": "http://www.lgbce.org.uk/all-reviews/york",
        "status": None,
        "latest_event": None,
        "boundaries_url": None,
        "legislation_url": None,
        "legislation_made": 0,
        "legislation_title": None,
    },
}
