# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-14 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SnoopedElection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.URLField(blank=True)),
                ('snooper_name', models.CharField(blank=True, max_length=100)),
                ('title', models.CharField(blank=True, max_length=800)),
                ('date', models.DateField()),
                ('cause', models.CharField(blank=True, max_length=800)),
                ('detail_url', models.URLField(blank=True)),
                ('detail', models.TextField(blank=True)),
            ],
        ),
    ]
