# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-14 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("election_snooper", "0002_auto_20170314_1754")]

    operations = [
        migrations.AddField(
            model_name="snoopedelection",
            name="extra",
            field=models.TextField(blank=True),
        )
    ]
