# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-27 12:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("election_snooper", "0006_auto_20170717_1355")]

    operations = [
        migrations.RemoveField(model_name="snoopedelection", name="election")
    ]
