version: 2.1

orbs:
  node: circleci/node@5.0.2

jobs:
  build:
    docker:
      - image: cimg/python:3.10
        environment:
          CIRCLECI: true
          PGHOST: 127.0.0.1
      - image: cimg/postgres:11.17-postgis
        environment:
          POSTGRES_USER: every_election
          POSTGRES_DB: every_election

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          key: v2--dependencies-{{ checksum "requirements/base.txt" }}-{{ checksum "requirements/testing.txt" }}


      - node/install:
          node-version: '10.19.0'
      - node/install-packages:
          cache-path: ~/repo/node_modules
          override-ci-command: npm install

      - run:
          name: install dependencies
          command: |
            sudo apt update && sudo apt install -y gdal-bin python3-gdal python3-dev
            python -m venv .venv
            . .venv/bin/activate
            pip install --upgrade pip
            pip install coveralls wheel
            pip install -r requirements/testing.txt
      - save_cache:
          paths:
            - ./.venv
            - ./node_modules
          key: v2-dependencies-{{ checksum "requirements/base.txt" }}-{{ checksum "requirements/testing.txt" }}

      - run:
          name: Tests
          command: |
            . .venv/bin/activate
            pip check
            python --version
            python manage.py --version
            python manage.py check
            pytest --flakes
            black --check .
            python manage.py makemigrations --check
      - run:
          name: Coverage
          command: |
            . .venv/bin/activate
            pytest --cov-report= --cov=every_election
            coveralls
