# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-11 07:37
from __future__ import unicode_literals

from django.db import migrations
from elections.constants import ELECTION_TYPES


def add_initial_election_types(apps, schema_editor):
    ElectionType = apps.get_model("elections", "ElectionType")
    ElectionSubType = apps.get_model("elections", "ElectionSubType")

    for type_name, info in ELECTION_TYPES.items():
        election_type, _ = ElectionType.objects.update_or_create(
            election_type=type_name, defaults={"name": info["name"]}
        )
        for subtype in info["subtypes"]:
            ElectionSubType.objects.update_or_create(
                election_type=election_type,
                election_subtype=subtype["election_subtype"],
                defaults={"name": subtype["name"]},
            )


def remove_initial_election_types(apps, schema_editor):
    ElectionType = apps.get_model("elections", "ElectionType")

    ElectionType.objects.filter(
        election_type__in=ELECTION_TYPES.keys()
    ).delete()


class Migration(migrations.Migration):
    dependencies = [("elections", "0002_auto_20161011_0741")]

    operations = [
        migrations.RunPython(
            add_initial_election_types, remove_initial_election_types
        )
    ]
