# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("elections", "0005_auto_20161021_1609")]

    operations = [
        migrations.AddField(
            model_name="election",
            name="suggested_status",
            field=models.CharField(
                choices=[
                    ("rejected", "Rejected"),
                    ("suggested", "Suggested"),
                    ("accepted", "Accepted"),
                ],
                default="Suggested",
                max_length=255,
            ),
        )
    ]
