# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("elections", "0006_election_suggested_status")]

    operations = [
        migrations.AlterField(
            model_name="election",
            name="election_id",
            field=models.CharField(max_length=100),
        )
    ]
