# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("elections", "0007_auto_20161021_1752")]

    operations = [
        migrations.AddField(
            model_name="election",
            name="rejection_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="election",
            name="suggestion_reason",
            field=models.TextField(blank=True),
        ),
    ]
