# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("elections", "0008_auto_20161021_1801")]

    operations = [
        migrations.AlterField(
            model_name="electiontype",
            name="election_type",
            field=models.CharField(blank=True, max_length=100, unique=True),
        )
    ]
