# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-10 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("elections", "0016_auto_20170109_1514")]

    operations = [
        migrations.AddField(
            model_name="election",
            name="election_title",
            field=models.CharField(blank=True, max_length=255),
        )
    ]
