# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-10 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("elections", "0018_election_group_type")]

    operations = [
        migrations.AlterField(
            model_name="election",
            name="group_type",
            field=models.CharField(blank=True, max_length=100, null=True),
        )
    ]
