# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-25 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("elections", "0020_auto_20170110_1556")]

    operations = [
        migrations.CreateModel(
            name="VotingSystem",
            fields=[
                ("slug", models.SlugField(primary_key=True, serialize=False)),
                ("name", models.CharField(blank=True, max_length=100)),
                ("wikipedia_url", models.URLField(blank=True)),
                ("description", models.TextField(blank=True)),
            ],
        ),
    ]
