# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-02 11:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("organisations", "0024_auto_20170210_1537"),
        ("elections", "0024_auto_20170224_1609"),
    ]

    operations = [
        migrations.AddField(
            model_name="election",
            name="geography",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="organisations.DivisionGeography",
            ),
        )
    ]
