# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 17:10
from __future__ import unicode_literals

from django.db import migrations

from elections import constants


class Migration(migrations.Migration):
    dependencies = [("elections", "0025_election_geography")]

    operations = [
        migrations.RunPython(
            migrations.RunPython.noop, migrations.RunPython.noop
        )
    ]
