# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-15 13:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("elections", "0026_set_default_voting_system")]

    operations = [
        migrations.AlterModelOptions(
            name="election", options={"ordering": ("election_id",)}
        )
    ]
