# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-24 08:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("elections", "0026_set_default_voting_system")]

    operations = [
        migrations.AddField(
            model_name="election",
            name="current",
            field=models.BooleanField(null=True),
        )
    ]
