# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-15 13:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("elections", "0027_auto_20170415_1308")]

    operations = [
        migrations.CreateModel(
            name="Explanation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=100)),
                ("explanation", models.TextField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name="election",
            name="explanation",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="elections.Explanation",
            ),
        ),
    ]
