# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-27 09:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("elections", "0032_auto_20170726_1526")]

    operations = [
        migrations.AddField(
            model_name="election",
            name="source",
            field=models.CharField(blank=True, max_length=1000),
        )
    ]
