# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-27 13:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0035_election_snooped_election'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election',
            name='snooped_election',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='election_snooper.SnoopedElection'),
        ),
    ]
