# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-01-26 16:12
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("elections", "0036_auto_20170727_1306")]

    operations = [
        migrations.AlterField(
            model_name="election",
            name="snooped_election",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="election_snooper.SnoopedElection",
            ),
        )
    ]
