# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-07 11:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("organisations", "0040_end_date_constraint"),
        ("elections", "0040_auto_20180518_1053"),
    ]

    operations = [
        migrations.RenameField(
            model_name="election",
            old_name="geography",
            new_name="division_geography",
        ),
        migrations.AddField(
            model_name="election",
            name="organisation_geography",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="organisations.OrganisationGeography",
            ),
        ),
    ]
