# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-20 16:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0042_split_geography_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electedrole',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='electedrole', to='organisations.Organisation'),
        ),
    ]
