# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-05 14:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("elections", "0049_move_status")]

    operations = [
        migrations.RemoveField(model_name="election", name="rejection_reason"),
        migrations.RemoveField(model_name="election", name="suggested_status"),
        migrations.RemoveField(model_name="election", name="suggestion_reason"),
    ]
