# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-05 16:18
from __future__ import unicode_literals

import elections.managers
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("elections", "0050_auto_20181005_1425")]

    operations = [
        migrations.AlterModelManagers(
            name="election",
            managers=[
                (
                    "private_objects",
                    elections.managers.PrivateElectionsManager(),
                )
            ],
        )
    ]
