from django.db import migrations

election_title_map = {
    "mayor.bedford.2019-05-02": "Mayor of Bedford",
    "mayor.bedford.2021-01-01": "Mayor of Bedford",
    "mayor.bristol.2016-05-05": "Mayor of Bristol",
    "mayor.bristol.2020-05-07": "Mayor of Bristol",
    "mayor.bristol.2021-01-01": "Mayor of Bristol",
    "mayor.cambridgeshire-and-peterborough.2017-05-04": "Mayor of Cambridgeshire and Peterborough Combined Authority",
    "mayor.cambridgeshire-and-peterborough.2021-01-01": "Mayor of Cambridgeshire and Peterborough Combined Authority",
    "mayor.copeland.2019-05-02": "Mayor of Copeland",
    "mayor.copeland.2021-01-01": "Mayor of Copeland",
    "mayor.doncaster.2017-05-04": "Mayor of Doncaster Metropolitan Borough Council",
    "mayor.doncaster.2021-01-01": "Mayor of Doncaster Metropolitan Borough Council",
    "mayor.greater-manchester-ca.2017-05-04": "Mayor of Greater Manchester",
    "mayor.greater-manchester-ca.2020-05-07": "Mayor of Greater Manchester",
    "mayor.greater-manchester-ca.2021-01-01": "Mayor of Greater Manchester",
    "mayor.hackney.2018-05-03": "Mayor of Hackney",
    "mayor.hackney.2021-01-01": "Mayor of Hackney",
    "mayor.leicester.2019-05-02": "Mayor of Leicester",
    "mayor.leicester.2021-01-01": "Mayor of Leicester",
    "mayor.lewisham.2018-05-03": "Mayor of Lewisham",
    "mayor.lewisham.2021-01-01": "Mayor of Lewisham",
    "mayor.liverpool.2016-05-05": "Mayor of Liverpool",
    "mayor.liverpool.2020-05-07": "Mayor of Liverpool",
    "mayor.liverpool.2021-01-01": "Mayor of Liverpool",
    "mayor.liverpool-city-ca.2017-05-04": "Mayor of Liverpool City Region",
    "mayor.liverpool-city-ca.2020-05-07": "Mayor of Liverpool City Region",
    "mayor.liverpool-city-ca.2021-01-01": "Mayor of Liverpool City Region",
    "mayor.london.2016-05-05": "Mayor of London",
    "mayor.london.2020-05-07": "Mayor of London",
    "mayor.london.2021-01-01": "Mayor of London",
    "mayor.mansfield.2019-05-02": "Mayor of Mansfield",
    "mayor.mansfield.2021-01-01": "Mayor of Mansfield",
    "mayor.middlesbrough.2019-05-02": "Mayor of Middlesbrough",
    "mayor.middlesbrough.2021-01-01": "Mayor of Middlesbrough",
    "mayor.newham.2018-05-03": "Mayor of Newham",
    "mayor.newham.2021-01-01": "Mayor of Newham",
    "mayor.north-of-tyne.2019-05-02": "Mayor of the North of Tyne Combined Authority",
    "mayor.north-of-tyne.2021-01-01": "Mayor of the North of Tyne Combined Authority",
    "mayor.north-tyneside.2017-05-04": "Mayor of North Tyneside Council",
    "mayor.north-tyneside.2021-01-01": "Mayor of North Tyneside Council",
    "mayor.salford.2016-05-05": "Mayor of Salford",
    "mayor.salford.2020-05-07": "Mayor of Salford",
    "mayor.salford.2021-01-01": "Mayor of Salford",
    "mayor.sheffield-city-ca.2018-05-03": "Mayor of the Barnsley, Doncaster, Rotherham and Sheffield Combined Authority",
    "mayor.sheffield-city-ca.2021-01-01": "Mayor of the Barnsley, Doncaster, Rotherham and Sheffield Combined Authority",
    "mayor.tees-valley.2017-05-04": "Mayor of Tees Valley Combined Authority",
    "mayor.tees-valley.2020-05-07": "Mayor of Tees Valley Combined Authority",
    "mayor.tees-valley.2021-01-01": "Mayor of Tees Valley Combined Authority",
    "mayor.torbay.2021-01-01": "Mayor of Torbay",
    "mayor.tower-hamlets.2018-05-03": "Mayor of Tower Hamlets",
    "mayor.tower-hamlets.2021-01-01": "Mayor of Tower Hamlets",
    "mayor.watford.2018-05-03": "Mayor of Watford",
    "mayor.watford.2021-01-01": "Mayor of Watford",
    "mayor.west-midlands.2017-05-04": "Mayor of West Midlands Combined Authority",
    "mayor.west-midlands.2020-05-07": "Mayor of West Midlands Combined Authority",
    "mayor.west-midlands.2021-01-01": "Mayor of West Midlands Combined Authority",
    "mayor.west-of-england.2017-05-04": "Mayor of West of England Combined Authority",
    "mayor.west-of-england.2021-01-01": "Mayor of West of England Combined Authority",
    "gla.c.barnet-and-camden.2016-05-05": "Greater London Assembly elections (Constituencies) Barnet and Camden",
    "gla.c.bexley-and-bromley.2016-05-05": "Greater London Assembly elections (Constituencies) Bexley and Bromley",
    "gla.c.brent-and-harrow.2016-05-05": "Greater London Assembly elections (Constituencies) Brent and Harrow",
    "gla.c.city-and-east.2016-05-05": "Greater London Assembly elections (Constituencies) City and East",
    "gla.c.croydon-and-sutton.2016-05-05": "Greater London Assembly elections (Constituencies) Croydon and Sutton",
    "gla.c.ealing-and-hillingdon.2016-05-05": "Greater London Assembly elections (Constituencies) Ealing and Hillingdon",
    "gla.c.enfield-and-haringey.2016-05-05": "Greater London Assembly elections (Constituencies) Enfield and Haringey",
    "gla.c.greenwich-and-lewisham.2016-05-05": "Greater London Assembly elections (Constituencies) Greenwich and Lewisham",
    "gla.c.havering-and-redbridge.2016-05-05": "Greater London Assembly elections (Constituencies) Havering and Redbridge",
    "gla.c.lambeth-and-southwark.2016-05-05": "Greater London Assembly elections (Constituencies) Lambeth and Southwark",
    "gla.c.merton-and-wandsworth.2016-05-05": "Greater London Assembly elections (Constituencies) Merton and Wandsworth",
    "gla.c.north-east.2016-05-05": "Greater London Assembly elections (Constituencies) North East",
    "gla.c.south-west.2016-05-05": "Greater London Assembly elections (Constituencies) South West",
    "gla.c.west-central.2016-05-05": "Greater London Assembly elections (Constituencies) West Central",
    "gla.c.barnet-and-camden.2020-05-07": "Greater London Assembly elections (Constituencies) Barnet and Camden",
    "gla.c.bexley-and-bromley.2020-05-07": "Greater London Assembly elections (Constituencies) Bexley and Bromley",
    "gla.c.brent-and-harrow.2020-05-07": "Greater London Assembly elections (Constituencies) Brent and Harrow",
    "gla.c.city-and-east.2020-05-07": "Greater London Assembly elections (Constituencies) City and East",
    "gla.c.croydon-and-sutton.2020-05-07": "Greater London Assembly elections (Constituencies) Croydon and Sutton",
    "gla.c.ealing-and-hillingdon.2020-05-07": "Greater London Assembly elections (Constituencies) Ealing and Hillingdon",
    "gla.c.enfield-and-haringey.2020-05-07": "Greater London Assembly elections (Constituencies) Enfield and Haringey",
    "gla.c.greenwich-and-lewisham.2020-05-07": "Greater London Assembly elections (Constituencies) Greenwich and Lewisham",
    "gla.c.havering-and-redbridge.2020-05-07": "Greater London Assembly elections (Constituencies) Havering and Redbridge",
    "gla.c.lambeth-and-southwark.2020-05-07": "Greater London Assembly elections (Constituencies) Lambeth and Southwark",
    "gla.c.merton-and-wandsworth.2020-05-07": "Greater London Assembly elections (Constituencies) Merton and Wandsworth",
    "gla.c.north-east.2020-05-07": "Greater London Assembly elections (Constituencies) North East",
    "gla.c.south-west.2020-05-07": "Greater London Assembly elections (Constituencies) South West",
    "gla.c.west-central.2020-05-07": "Greater London Assembly elections (Constituencies) West Central",
    "naw.c.aberavon.2016-05-05": "National Assembly for Wales elections (Constituencies) Aberavon",
    "naw.c.aberconwy.2016-05-05": "National Assembly for Wales elections (Constituencies) Aberconwy",
    "naw.c.alyn-and-deeside.2016-05-05": "National Assembly for Wales elections (Constituencies) Alyn and Deeside",
    "naw.c.arfon.2016-05-05": "National Assembly for Wales elections (Constituencies) Arfon",
    "naw.c.blaenau-gwent.2016-05-05": "National Assembly for Wales elections (Constituencies) Blaenau Gwent",
    "naw.c.brecon-and-radnorshire.2016-05-05": "National Assembly for Wales elections (Constituencies) Brecon and Radnorshire",
    "naw.c.bridgend.2016-05-05": "National Assembly for Wales elections (Constituencies) Bridgend",
    "naw.c.caerphilly.2016-05-05": "National Assembly for Wales elections (Constituencies) Caerphilly",
    "naw.c.cardiff-central.2016-05-05": "National Assembly for Wales elections (Constituencies) Cardiff Central",
    "naw.c.cardiff-north.2016-05-05": "National Assembly for Wales elections (Constituencies) Cardiff North",
    "naw.c.cardiff-south-and-penarth.2016-05-05": "National Assembly for Wales elections (Constituencies) Cardiff South and Penarth",
    "naw.c.cardiff-west.2016-05-05": "National Assembly for Wales elections (Constituencies) Cardiff West",
    "naw.c.carmarthen-east-and-dinefwr.2016-05-05": "National Assembly for Wales elections (Constituencies) Carmarthen East and Dinefwr",
    "naw.c.carmarthen-west-and-south-pembrokeshire.2016-05-05": "National Assembly for Wales elections (Constituencies) Carmarthen West and South Pembrokeshire",
    "naw.c.ceredigion.2016-05-05": "National Assembly for Wales elections (Constituencies) Ceredigion",
    "naw.c.clwyd-south.2016-05-05": "National Assembly for Wales elections (Constituencies) Clwyd South",
    "naw.c.clwyd-west.2016-05-05": "National Assembly for Wales elections (Constituencies) Clwyd West",
    "naw.c.cynon-valley.2016-05-05": "National Assembly for Wales elections (Constituencies) Cynon Valley",
    "naw.c.delyn.2016-05-05": "National Assembly for Wales elections (Constituencies) Delyn",
    "naw.c.dwyfor-meirionnydd.2016-05-05": "National Assembly for Wales elections (Constituencies) Dwyfor Meirionnydd",
    "naw.c.gower.2016-05-05": "National Assembly for Wales elections (Constituencies) Gower",
    "naw.c.islwyn.2016-05-05": "National Assembly for Wales elections (Constituencies) Islwyn",
    "naw.c.llanelli.2016-05-05": "National Assembly for Wales elections (Constituencies) Llanelli",
    "naw.c.merthyr-tydfil-and-rhymney.2016-05-05": "National Assembly for Wales elections (Constituencies) Merthyr Tydfil and Rhymney",
    "naw.c.monmouth.2016-05-05": "National Assembly for Wales elections (Constituencies) Monmouth",
    "naw.c.montgomeryshire.2016-05-05": "National Assembly for Wales elections (Constituencies) Montgomeryshire",
    "naw.c.neath.2016-05-05": "National Assembly for Wales elections (Constituencies) Neath",
    "naw.c.newport-east.2016-05-05": "National Assembly for Wales elections (Constituencies) Newport East",
    "naw.c.newport-west.2016-05-05": "National Assembly for Wales elections (Constituencies) Newport West",
    "naw.c.ogmore.2016-05-05": "National Assembly for Wales elections (Constituencies) Ogmore",
    "naw.c.pontypridd.2016-05-05": "National Assembly for Wales elections (Constituencies) Pontypridd",
    "naw.c.preseli-pembrokeshire.2016-05-05": "National Assembly for Wales elections (Constituencies) Preseli Pembrokeshire",
    "naw.c.rhondda.2016-05-05": "National Assembly for Wales elections (Constituencies) Rhondda",
    "naw.c.swansea-east.2016-05-05": "National Assembly for Wales elections (Constituencies) Swansea East",
    "naw.c.swansea-west.2016-05-05": "National Assembly for Wales elections (Constituencies) Swansea West",
    "naw.c.torfaen.2016-05-05": "National Assembly for Wales elections (Constituencies) Torfaen",
    "naw.c.vale-of-clwyd.2016-05-05": "National Assembly for Wales elections (Constituencies) Vale of Clwyd",
    "naw.c.vale-of-glamorgan.2016-05-05": "National Assembly for Wales elections (Constituencies) Vale of Glamorgan",
    "naw.c.wrexham.2016-05-05": "National Assembly for Wales elections (Constituencies) Wrexham",
    "naw.c.ynys-mon.2016-05-05": "National Assembly for Wales elections (Constituencies) Ynys Môn",
    "naw.c.alyn-and-deeside.by.2018-02-06": "National Assembly for Wales election (Constituencies) Alyn and Deeside by-election",
    "naw.r.mid-and-west-wales.2016-05-05": "National Assembly for Wales elections (Regions) Mid and West Wales",
    "naw.r.north-wales.2016-05-05": "National Assembly for Wales elections (Regions) North Wales",
    "naw.r.south-wales-central.2016-05-05": "National Assembly for Wales elections (Regions) South Wales Central",
    "naw.r.south-wales-east.2016-05-05": "National Assembly for Wales elections (Regions) South Wales East",
    "naw.r.south-wales-west.2016-05-05": "National Assembly for Wales elections (Regions) South Wales West",
    "sp.c.aberdeen-central.2016-05-05": "Scottish Parliament elections (Constituencies) Aberdeen Central",
    "sp.c.aberdeen-donside.2016-05-05": "Scottish Parliament elections (Constituencies) Aberdeen Donside",
    "sp.c.aberdeenshire-east.2016-05-05": "Scottish Parliament elections (Constituencies) Aberdeenshire East",
    "sp.c.aberdeenshire-west.2016-05-05": "Scottish Parliament elections (Constituencies) Aberdeenshire West",
    "sp.c.aberdeen-south-and-north-kincardine.2016-05-05": "Scottish Parliament elections (Constituencies) Aberdeen South and North Kincardine",
    "sp.c.airdrie-and-shotts.2016-05-05": "Scottish Parliament elections (Constituencies) Airdrie and Shotts",
    "sp.c.almond-valley.2016-05-05": "Scottish Parliament elections (Constituencies) Almond Valley",
    "sp.c.angus-north-and-mearns.2016-05-05": "Scottish Parliament elections (Constituencies) Angus North and Mearns",
    "sp.c.angus-south.2016-05-05": "Scottish Parliament elections (Constituencies) Angus South",
    "sp.c.argyll-and-bute.2016-05-05": "Scottish Parliament elections (Constituencies) Argyll and Bute",
    "sp.c.ayr.2016-05-05": "Scottish Parliament elections (Constituencies) Ayr",
    "sp.c.banffshire-and-buchan-coast.2016-05-05": "Scottish Parliament elections (Constituencies) Banffshire and Buchan Coast",
    "sp.c.caithness-sutherland-and-ross.2016-05-05": "Scottish Parliament elections (Constituencies) Caithness, Sutherland and Ross",
    "sp.c.carrick-cumnock-and-doon-valley.2016-05-05": "Scottish Parliament elections (Constituencies) Carrick, Cumnock and Doon Valley",
    "sp.c.clackmannanshire-and-dunblane.2016-05-05": "Scottish Parliament elections (Constituencies) Clackmannanshire and Dunblane",
    "sp.c.clydebank-and-milngavie.2016-05-05": "Scottish Parliament elections (Constituencies) Clydebank and Milngavie",
    "sp.c.clydesdale.2016-05-05": "Scottish Parliament elections (Constituencies) Clydesdale",
    "sp.c.coatbridge-and-chryston.2016-05-05": "Scottish Parliament elections (Constituencies) Coatbridge and Chryston",
    "sp.c.cowdenbeath.2016-05-05": "Scottish Parliament elections (Constituencies) Cowdenbeath",
    "sp.c.cumbernauld-and-kilsyth.2016-05-05": "Scottish Parliament elections (Constituencies) Cumbernauld and Kilsyth",
    "sp.c.cunninghame-north.2016-05-05": "Scottish Parliament elections (Constituencies) Cunninghame North",
    "sp.c.cunninghame-south.2016-05-05": "Scottish Parliament elections (Constituencies) Cunninghame South",
    "sp.c.dumbarton.2016-05-05": "Scottish Parliament elections (Constituencies) Dumbarton",
    "sp.c.dumfriesshire.2016-05-05": "Scottish Parliament elections (Constituencies) Dumfriesshire",
    "sp.c.dundee-city-east.2016-05-05": "Scottish Parliament elections (Constituencies) Dundee City East",
    "sp.c.dundee-city-west.2016-05-05": "Scottish Parliament elections (Constituencies) Dundee City West",
    "sp.c.dunfermline.2016-05-05": "Scottish Parliament elections (Constituencies) Dunfermline",
    "sp.c.east-kilbride.2016-05-05": "Scottish Parliament elections (Constituencies) East Kilbride",
    "sp.c.east-lothian.2016-05-05": "Scottish Parliament elections (Constituencies) East Lothian",
    "sp.c.eastwood.2016-05-05": "Scottish Parliament elections (Constituencies) Eastwood",
    "sp.c.edinburgh-central.2016-05-05": "Scottish Parliament elections (Constituencies) Edinburgh Central",
    "sp.c.edinburgh-eastern.2016-05-05": "Scottish Parliament elections (Constituencies) Edinburgh Eastern",
    "sp.c.edinburgh-northern-and-leith.2016-05-05": "Scottish Parliament elections (Constituencies) Edinburgh Northern and Leith",
    "sp.c.edinburgh-pentlands.2016-05-05": "Scottish Parliament elections (Constituencies) Edinburgh Pentlands",
    "sp.c.edinburgh-southern.2016-05-05": "Scottish Parliament elections (Constituencies) Edinburgh Southern",
    "sp.c.edinburgh-western.2016-05-05": "Scottish Parliament elections (Constituencies) Edinburgh Western",
    "sp.c.ettrick-roxburgh-and-berwickshire.2016-05-05": "Scottish Parliament elections (Constituencies) Ettrick, Roxburgh and Berwickshire",
    "sp.c.falkirk-east.2016-05-05": "Scottish Parliament elections (Constituencies) Falkirk East",
    "sp.c.falkirk-west.2016-05-05": "Scottish Parliament elections (Constituencies) Falkirk West",
    "sp.c.galloway-and-west-dumfries.2016-05-05": "Scottish Parliament elections (Constituencies) Galloway and West Dumfries",
    "sp.c.glasgow-anniesland.2016-05-05": "Scottish Parliament elections (Constituencies) Glasgow Anniesland",
    "sp.c.glasgow-cathcart.2016-05-05": "Scottish Parliament elections (Constituencies) Glasgow Cathcart",
    "sp.c.glasgow-kelvin.2016-05-05": "Scottish Parliament elections (Constituencies) Glasgow Kelvin",
    "sp.c.glasgow-maryhill-and-springburn.2016-05-05": "Scottish Parliament elections (Constituencies) Glasgow Maryhill and Springburn",
    "sp.c.glasgow-pollok.2016-05-05": "Scottish Parliament elections (Constituencies) Glasgow Pollok",
    "sp.c.glasgow-provan.2016-05-05": "Scottish Parliament elections (Constituencies) Glasgow Provan",
    "sp.c.glasgow-shettleston.2016-05-05": "Scottish Parliament elections (Constituencies) Glasgow Shettleston",
    "sp.c.glasgow-southside.2016-05-05": "Scottish Parliament elections (Constituencies) Glasgow Southside",
    "sp.c.greenock-and-inverclyde.2016-05-05": "Scottish Parliament elections (Constituencies) Greenock and Inverclyde",
    "sp.c.hamilton-larkhall-and-stonehouse.2016-05-05": "Scottish Parliament elections (Constituencies) Hamilton, Larkhall and Stonehouse",
    "sp.c.inverness-and-nairn.2016-05-05": "Scottish Parliament elections (Constituencies) Inverness and Nairn",
    "sp.c.kilmarnock-and-irvine-valley.2016-05-05": "Scottish Parliament elections (Constituencies) Kilmarnock and Irvine Valley",
    "sp.c.kirkcaldy.2016-05-05": "Scottish Parliament elections (Constituencies) Kirkcaldy",
    "sp.c.linlithgow.2016-05-05": "Scottish Parliament elections (Constituencies) Linlithgow",
    "sp.c.mid-fife-and-glenrothes.2016-05-05": "Scottish Parliament elections (Constituencies) Mid Fife and Glenrothes",
    "sp.c.midlothian-north-and-musselburgh.2016-05-05": "Scottish Parliament elections (Constituencies) Midlothian North and Musselburgh",
    "sp.c.midlothian-south-tweeddale-and-lauderdale.2016-05-05": "Scottish Parliament elections (Constituencies) Midlothian South, Tweeddale and Lauderdale",
    "sp.c.moray.2016-05-05": "Scottish Parliament elections (Constituencies) Moray",
    "sp.c.motherwell-and-wishaw.2016-05-05": "Scottish Parliament elections (Constituencies) Motherwell and Wishaw",
    "sp.c.na-h-eileanan-an-iar.2016-05-05": "Scottish Parliament elections (Constituencies) Na h-Eileanan an Iar",
    "sp.c.north-east-fife.2016-05-05": "Scottish Parliament elections (Constituencies) North East Fife",
    "sp.c.orkney-islands.2016-05-05": "Scottish Parliament elections (Constituencies) Orkney Islands",
    "sp.c.paisley.2016-05-05": "Scottish Parliament elections (Constituencies) Paisley",
    "sp.c.perthshire-north.2016-05-05": "Scottish Parliament elections (Constituencies) Perthshire North",
    "sp.c.perthshire-south-and-kinross-shire.2016-05-05": "Scottish Parliament elections (Constituencies) Perthshire South and Kinross-shire",
    "sp.c.renfrewshire-north-and-west.2016-05-05": "Scottish Parliament elections (Constituencies) Renfrewshire North and West",
    "sp.c.renfrewshire-south.2016-05-05": "Scottish Parliament elections (Constituencies) Renfrewshire South",
    "sp.c.rutherglen.2016-05-05": "Scottish Parliament elections (Constituencies) Rutherglen",
    "sp.c.shetland-islands.2016-05-05": "Scottish Parliament elections (Constituencies) Shetland Islands",
    "sp.c.skye-lochaber-and-badenoch.2016-05-05": "Scottish Parliament elections (Constituencies) Skye, Lochaber and Badenoch",
    "sp.c.stirling.2016-05-05": "Scottish Parliament elections (Constituencies) Stirling",
    "sp.c.strathkelvin-and-bearsden.2016-05-05": "Scottish Parliament elections (Constituencies) Strathkelvin and Bearsden",
    "sp.c.uddingston-and-bellshill.2016-05-05": "Scottish Parliament elections (Constituencies) Uddingston and Bellshill",
    "sp.c.shetland-islands.by.2019-08-29": "Scottish Parliament elections (Constituencies) Shetland Islands by-election",
    "sp.r.central-scotland.2016-05-05": "Scottish Parliament elections (Regions) Central Scotland",
    "sp.r.glasgow.2016-05-05": "Scottish Parliament elections (Regions) Glasgow",
    "sp.r.highlands-and-islands.2016-05-05": "Scottish Parliament elections (Regions) Highlands and Islands",
    "sp.r.lothian.2016-05-05": "Scottish Parliament elections (Regions) Lothian",
    "sp.r.mid-scotland-and-fife.2016-05-05": "Scottish Parliament elections (Regions) Mid Scotland and Fife",
    "sp.r.north-east-scotland.2016-05-05": "Scottish Parliament elections (Regions) North East Scotland",
    "sp.r.south-scotland.2016-05-05": "Scottish Parliament elections (Regions) South Scotland",
    "sp.r.west-scotland.2016-05-05": "Scottish Parliament elections (Regions) West Scotland",
}


def fix_old_election_titles(apps, schema_editor):
    for election_id, title in election_title_map.items():
        Election = apps.get_model("elections", "Election")
        try:
            e = Election.private_objects.get(election_id=election_id)
            e.election_title = title
            e.save()
        except Election.DoesNotExist:
            # don't throw an exception
            # if we're initializing an enpty DB
            pass


class Migration(migrations.Migration):

    dependencies = [
        ("elections", "0056_cleanup_group_types"),
    ]

    operations = [
        migrations.RunPython(fix_old_election_titles, migrations.RunPython.noop)
    ]
