# Generated by Django 2.2.10 on 2020-02-18 08:36

from django.db import migrations


def remove_gla_a_subtype(apps, schema_editor):
    Election = apps.get_model("elections", "Election")
    qs = Election.private_objects.filter(election_id__startswith="gla.a.")
    qs.update(group_type=None, update_modified=False)


class Migration(migrations.Migration):
    dependencies = [("elections", "0057_cleanup_mayor_subtype_titles")]

    operations = [migrations.RunPython(remove_gla_a_subtype, migrations.RunPython.noop)]
