# Generated by Django 2.2.16 on 2021-02-13 12:11

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("elections", "0058_set-gla-a-to-ballot"),
    ]

    operations = [
        migrations.AddField(
            model_name="election",
            name="tags",
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
