# Generated by Django 4.1 on 2022-09-14 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elections", "0062_add_created_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="explanation",
            name="explanation",
            field=models.CharField(max_length=100),
        ),
    ]
