# Generated by Django 4.1.5 on 2023-01-25 10:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("elections", "0063_alter_explanation_explanation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="election",
            name="voting_system",
            field=models.CharField(
                choices=[
                    ("AMS", "Additional Member System"),
                    ("FPTP", "First-past-the-post"),
                    ("sv", "Supplementary Vote"),
                    ("STV", "Single Transferable Vote"),
                    ("PR-CL", "Closed List"),
                ],
                max_length=100,
                null=True,
            ),
        ),
    ]
