# Generated by Django 4.1.5 on 2023-03-01 15:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "elections",
            "0065_remove_electiontype_default_voting_system_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="explanation",
            name="explanation",
            field=models.TextField(),
        ),
    ]
