# Generated by Django 4.1.7 on 2023-03-10 16:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("elections", "0066_alter_explanation_explanation"),
    ]

    operations = [
        migrations.AddField(
            model_name="election",
            name="requires_voter_id",
            field=models.CharField(
                choices=[
                    ("EFA-2002", "Electoral Fraud (Northern Ireland) Act 2002"),
                    ("EA-2022", "Elections Act 2022"),
                    ("pilot-2018", "2018 voter ID pilot scheme"),
                    ("pilot-2019", "2018 voter ID pilot scheme"),
                ],
                max_length=100,
                null=True,
            ),
        ),
    ]
