# Generated by Django 4.1.7 on 2023-03-10 16:47

from django.db import migrations
from elections.utils import get_voter_id_requirement


def set_voter_id_requirements(apps, schema_editor):
    Election = apps.get_model("elections", "Election")

    all_elections = Election.private_objects.all()

    for election in all_elections:
        election.requires_voter_id = get_voter_id_requirement(election)
        election.save()


class Migration(migrations.Migration):

    dependencies = [
        ("elections", "0067_election_requires_voter_id"),
    ]

    operations = [
        migrations.RunPython(set_voter_id_requirements, migrations.RunPython.noop)
    ]
