# Generated by Django 2.2.24 on 2022-07-19 21:44

from django.db import migrations, models
import elections.models


class Migration(migrations.Migration):

    dependencies = [
        ("elections", "0068_backfill_voter_id_requirements"),
    ]

    operations = [
        migrations.AddField(
            model_name="election",
            name="current_status",
            field=models.CharField(
                choices=[
                    (elections.models.ModerationStatuses("Suggested"), "Suggested"),
                    (elections.models.ModerationStatuses("Rejected"), "Rejected"),
                    (elections.models.ModerationStatuses("Approved"), "Approved"),
                    (elections.models.ModerationStatuses("Deleted"), "Deleted"),
                ],
                default="Suggested",
                max_length=32,
                db_index=True,
            ),
        ),
    ]
