# Generated by Django 4.1.7 on 2023-03-15 13:31

import django.db.models.manager
import elections.managers
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("elections", "0070_populate_current_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="ElectionStatusProblem",
            fields=[],
            options={
                "verbose_name_plural": "⚠️ Current status Problems",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("elections.election",),
            managers=[
                ("objects", django.db.models.manager.Manager()),
                (
                    "private_objects",
                    elections.managers.PrivateElectionsManager(),
                ),
            ],
        ),
    ]
