# Generated by Django 4.1.7 on 2023-03-21 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elections", "0071_electionstatusproblem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="election",
            name="current",
            field=models.BooleanField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="election",
            name="group_type",
            field=models.CharField(
                blank=True, db_index=True, max_length=100, null=True
            ),
        ),
    ]
