# Generated by Django 4.2.3 on 2023-08-07 13:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("elections", "0072_alter_election_current_alter_election_group_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="election",
            name="requires_voter_id",
            field=models.CharField(
                choices=[
                    ("EFA-2002", "Electoral Fraud (Northern Ireland) Act 2002"),
                    ("EA-2022", "Elections Act 2022"),
                    ("pilot-2018", "2018 voter ID pilot scheme"),
                    ("pilot-2019", "2019 voter ID pilot scheme"),
                ],
                max_length=100,
                null=True,
            ),
        ),
    ]
