# Generated by Django 4.2.6 on 2023-11-22 21:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("elections", "0075_alter_election_group"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="election",
            options={"get_latest_by": "modified", "ordering": ("election_id",)},
        ),
    ]
