# Generated by Django 4.2.6 on 2023-11-02 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("elections", "0075_set_cancellation_reason"),
    ]

    operations = [
        migrations.AlterField(
            model_name="election",
            name="group",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="_children_qs",
                to="elections.election",
                verbose_name="Parent",
            ),
        ),
    ]
