# Generated by Django 4.2.16 on 2024-11-28 15:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("elections", "0076_alter_election_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="election",
            name="requires_voter_id",
            field=models.CharField(
                blank=True,
                choices=[
                    (None, "No ID Required"),
                    ("EFA-2002", "Electoral Fraud (Northern Ireland) Act 2002"),
                    ("EA-2022", "Elections Act 2022"),
                    ("pilot-2018", "2018 voter ID pilot scheme"),
                    ("pilot-2019", "2019 voter ID pilot scheme"),
                ],
                max_length=100,
                null=True,
            ),
        ),
    ]
