# Generated by Django 4.2.22 on 2025-06-20 10:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("elections", "0077_alter_election_requires_voter_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="election",
            name="by_election_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("DEATH", "The elected member died"),
                    ("RESIGNATION", "The elected member resigned"),
                    (
                        "ELECTORAL_COURT",
                        "The election of the elected member was declared void by an election court",
                    ),
                    (
                        "FAILURE_TO_ACCEPT",
                        "The previous election winner did not sign a declaration of acceptance",
                    ),
                    (
                        "FAILURE_TO_ATTEND_MEETINGS",
                        "The elected member failed to attend meetings for six months",
                    ),
                    ("DISQUALIFICATION", "The elected member was disqualified"),
                    (
                        "LOSING_QUALIFICATION",
                        "The elected member no longer qualified as a registered elector",
                    ),
                    (
                        "RECALL_PETITION",
                        "The elected member was recalled by a successful recall petition",
                    ),
                    ("OTHER", "Other"),
                ],
                default=None,
                max_length=30,
                null=True,
            ),
        ),
    ]
