# Generated by Django 4.2.22 on 2025-07-17 15:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("elections", "0079_alter_election_by_election_reason"),
    ]

    operations = [
        migrations.AlterField(
            model_name="election",
            name="voting_system",
            field=models.CharField(
                choices=[
                    ("AMS", "Additional Member System (Party List)"),
                    ("FPTP", "First-past-the-post"),
                    ("sv", "Supplementary Vote"),
                    ("STV", "Single Transferable Vote"),
                    ("PR-CL", "Closed List"),
                ],
                max_length=100,
                null=True,
            ),
        ),
    ]
