# Generated by Django 4.2.22 on 2025-08-07 13:13

from django.db import migrations
from elections.models import Election


def update_by_election_reasons(apps, schema_editor):
    # For existing by-elections where the current reason is an empty string
    # set reason to 'UNKNOWN'
    Election.private_objects.filter(
        group_type=None,
        by_election_reason="",
        election_id__contains=".by.",
    ).update(by_election_reason="UNKNOWN")

    # All other elections (non-by-elections) keep the empty string value
    # which now represents 'NOT_APPLICABLE'


def reverse_update_by_election_reasons(apps, schema_editor):
    # Reverse the migration by setting UNKNOWN reasons back to empty string,
    # but only for by-elections
    Election.private_objects.filter(
        group_type=None,
        by_election_reason="UNKNOWN",
        election_id__contains=".by.",
    ).update(by_election_reason="")


class Migration(migrations.Migration):
    dependencies = [
        ("elections", "0081_alter_election_by_election_reason"),
    ]

    operations = [
        migrations.RunPython(
            update_by_election_reasons, reverse_update_by_election_reasons
        ),
    ]
