# Generated by Django 5.2.13 on 2026-06-03 11:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("elections", "0083_alter_election_by_election_reason"),
    ]

    operations = [
        migrations.AlterField(
            model_name="election",
            name="by_election_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("DEATH", "The elected member died"),
                    ("RESIGNATION", "The elected member resigned"),
                    (
                        "ELECTORAL_COURT",
                        "The election of the elected member was declared void by an election court",
                    ),
                    (
                        "FAILURE_TO_ACCEPT",
                        "The previous election winner did not sign a declaration of acceptance",
                    ),
                    (
                        "FAILURE_TO_ATTEND_MEETINGS",
                        "The elected member failed to attend meetings for six months",
                    ),
                    ("DISQUALIFICATION", "The elected member was disqualified"),
                    (
                        "LOSING_QUALIFICATION",
                        "The elected member no longer qualified as a registered elector",
                    ),
                    (
                        "RECALL_PETITION",
                        "The elected member was recalled by a successful recall petition",
                    ),
                    (
                        "ELECTED_COUNCIL_MAYOR",
                        "This by-election was called because the elected member was elected mayor of the council, and cannot hold both positions.",
                    ),
                    (
                        "ELECTED_PARLIAMENT",
                        "This by-election was called because the elected member was elected Member of the UK Parliament, and cannot hold both positions.",
                    ),
                    (
                        "ELECTED_STRATEGIC_AUTHORITY_MAYOR",
                        "This by-election was called because the elected member was elected mayor of a strategic authority, and cannot hold both positions.",
                    ),
                    (
                        "ELECTED_SENEDD",
                        "This by-election was called because the elected member was elected Member of the Senedd, and cannot hold both positions.",
                    ),
                    (
                        "ELECTED_SCOTTISH_PARLIAMENT",
                        "This by-election was called because the elected member was elected Member of the Scottish Parliament, and cannot hold both positions.",
                    ),
                    ("OTHER", "Other"),
                    ("UNKNOWN", "Unknown"),
                    ("", "Neither a by-election nor a ballot"),
                ],
                default="",
                max_length=40,
            ),
        ),
    ]
