# Generated by Django 5.2.13 on 2026-06-17 11:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("elections", "0085_alter_election_by_election_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="election",
            name="close_of_nominations",
            field=models.DateField(
                blank=True, help_text="Close of Nominations", null=True
            ),
        ),
        migrations.AddField(
            model_name="election",
            name="postal_vote_application_deadline",
            field=models.DateField(
                blank=True,
                help_text="Postal vote application deadline",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="election",
            name="registration_deadline",
            field=models.DateField(
                blank=True, help_text="Register to vote deadline", null=True
            ),
        ),
        migrations.AddField(
            model_name="election",
            name="vac_application_deadline",
            field=models.DateField(
                blank=True, help_text="VAC application deadline", null=True
            ),
        ),
    ]
