# Generated by Django 5.2.13 on 2026-06-16 10:30

from django.db import migrations
from uk_election_timetables.calendars import Country
from uk_election_timetables.election_ids import from_election_id

country_map = {
    "WLS": Country.WALES,
    "ENG": Country.ENGLAND,
    "NIR": Country.NORTHERN_IRELAND,
    "SCT": Country.SCOTLAND,
    "GBN": None,
}


def backfill_timetable_fields(apps, schema_editor):
    Election = apps.get_model("elections", "Election")
    for election in Election.private_objects.using(
        schema_editor.connection.alias
    ).all():
        # we can't calculate a timetable for en election with
        # no polling day
        if election.poll_open_date is None:
            continue

        # only calculate a timetable for ballots
        if election.group_type is not None:
            continue

        # We don't have logic for computing timetable for
        # EU Parliament elections but some do exist in the DB
        # from back in the day
        if election.election_id.startswith("europarl."):
            continue

        area = election.division or election.organisation
        territory_code = (
            area.territory_code or election.organisation.territory_code
        )

        timetable = from_election_id(
            election.election_id, country=country_map[territory_code]
        )

        election.postal_vote_application_deadline = (
            timetable.postal_vote_application_deadline
        )

        # Only set a VAC deadline if the election requires ID
        if election.requires_voter_id:
            election.vac_application_deadline = (
                timetable.vac_application_deadline
            )

        # There is no nominations or SOPN for refenda
        if not election.election_id.startswith("ref."):
            election.close_of_nominations = timetable.sopn_publish_date

        election.registration_deadline = timetable.registration_deadline

        election.save()


def clear_timetable_fields(apps, schema_editor):
    Election = apps.get_model("elections", "Election")
    Election.private_objects.using(schema_editor.connection.alias).update(
        postal_vote_application_deadline=None,
        vac_application_deadline=None,
        close_of_nominations=None,
        registration_deadline=None,
    )


class Migration(migrations.Migration):
    dependencies = [
        ("elections", "0086_timetable_fields"),
    ]

    operations = [
        migrations.RunPython(backfill_timetable_fields, clear_timetable_fields)
    ]
