# Generated by Django 5.2.13 on 2026-06-16 10:30

from django.db import migrations


def fix_ni_timetable_fields(apps, schema_editor):
    Election = apps.get_model("elections", "Election")
    Election.private_objects.using(schema_editor.connection.alias).filter(
        requires_voter_id="EFA-2002"
    ).update(vac_application_deadline=None)


class Migration(migrations.Migration):
    dependencies = [
        ("elections", "0087_backfill_timetable_fields"),
    ]

    operations = [
        migrations.RunPython(fix_ni_timetable_fields, migrations.RunPython.noop)
    ]
