# Generated by Django 5.2.15 on 2026-07-08 09:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("elections", "0088_fix_ni_timetable_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="election",
            name="notice_of_election_deadline",
            field=models.DateField(
                blank=True,
                help_text="Deadline to publish Notice of Election document",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="election",
            name="sopn_publish_deadline",
            field=models.DateField(
                blank=True,
                help_text="Deadline to publish SOPN document",
                null=True,
            ),
        ),
    ]
