# Generated by Django 5.2.13 on 2026-06-16 10:30

from django.db import migrations
from uk_election_timetables.calendars import Country
from uk_election_timetables.election_ids import from_election_id

country_map = {
    "WLS": Country.WALES,
    "ENG": Country.ENGLAND,
    "NIR": Country.NORTHERN_IRELAND,
    "SCT": Country.SCOTLAND,
    "GBN": None,
}


def backfill_new_timetable_fields(apps, schema_editor):
    Election = apps.get_model("elections", "Election")
    for election in Election.private_objects.using(
        schema_editor.connection.alias
    ).all():
        # we can't calculate a timetable for en election with
        # no polling day
        if election.poll_open_date is None:
            continue

        # only calculate a timetable for ballots
        if election.group_type is not None:
            continue

        # We don't have logic for computing timetable for
        # EU Parliament elections but some do exist in the DB
        # from back in the day
        if election.election_id.startswith("europarl."):
            continue

        # There is no nominations or SOPN for refenda
        # Notice of election deadline is applicable
        # but not implemented
        if election.election_id.startswith("ref."):
            continue

        area = election.division or election.organisation
        territory_code = (
            area.territory_code or election.organisation.territory_code
        )

        timetable = from_election_id(
            election.election_id, country=country_map[territory_code]
        )

        # populate the new fields we just added in 0089
        election.notice_of_election_deadline = (
            timetable.notice_of_election_deadline
        )
        election.sopn_publish_deadline = timetable.sopn_publish_deadline

        # We used to make a slightly different assumption about
        # City of London elections. This changed in 5.0.0 so
        # update close_of_nominations for City of London only
        if election.election_id.startswith("local.city-of-london."):
            election.close_of_nominations = timetable.close_of_nominations

        election.save()


def clear_new_timetable_fields(apps, schema_editor):
    Election = apps.get_model("elections", "Election")
    Election.private_objects.using(schema_editor.connection.alias).update(
        notice_of_election_deadline=None,
        sopn_publish_deadline=None,
    )


class Migration(migrations.Migration):
    dependencies = [
        ("elections", "0089_more_timetable_fields"),
    ]

    operations = [
        migrations.RunPython(
            backfill_new_timetable_fields, clear_new_timetable_fields
        )
    ]
