# Generated by Django 5.2.16 on 2026-08-13 06:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("elections", "0090_backfill_new_timetable_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="election",
            name="proxy_vote_application_deadline",
            field=models.DateField(
                blank=True,
                help_text="Proxy vote application deadline",
                null=True,
            ),
        ),
    ]
