# Generated by Django 5.2.16 on 2026-08-13 09:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("elections", "0091_election_proxy_vote_application_deadline"),
    ]

    operations = [
        migrations.AddField(
            model_name="election",
            name="replacement_pack_start_date",
            field=models.DateField(
                blank=True,
                help_text="First date electors can apply for a postal vote replacement pack",
                null=True,
            ),
        ),
    ]
