# Generated by Django 5.2.13 on 2026-06-16 10:30

from django.db import migrations
from uk_election_timetables.calendars import Country
from uk_election_timetables.election_ids import from_election_id

country_map = {
    "WLS": Country.WALES,
    "ENG": Country.ENGLAND,
    "NIR": Country.NORTHERN_IRELAND,
    "SCT": Country.SCOTLAND,
    "GBN": None,
}


def backfill_new_timetable_fields(apps, schema_editor):
    Election = apps.get_model("elections", "Election")
    qs = (
        Election.private_objects.using(schema_editor.connection.alias)
        # we can't calculate a timetable for an election with no polling day
        .filter(poll_open_date__isnull=False)
        # only calculate a timetable for ballots
        .filter(group_type__isnull=True)
        # We don't have logic for computing timetable for
        # EU Parliament elections but some do exist in the DB
        # from back in the day
        .exclude(election_id__startswith="europarl.")
        .select_related("division", "organisation")
    )

    elections_to_update = []

    for election in qs.iterator():
        area = election.division or election.organisation
        territory_code = (
            area.territory_code or election.organisation.territory_code
        )

        timetable = from_election_id(
            election.election_id, country=country_map[territory_code]
        )

        # populate the new fields we just added in 0090 and 0091
        if territory_code == "NIR" or election.election_id.startswith("sp."):
            election.replacement_pack_start_date = None
        else:
            election.replacement_pack_start_date = (
                timetable.replacement_pack_start_date
            )

        election.proxy_vote_application_deadline = (
            timetable.proxy_vote_application_deadline
        )

        elections_to_update.append(election)

    batch_size = 2000
    for i in range(0, len(elections_to_update), batch_size):
        qs.bulk_update(
            elections_to_update[i : i + batch_size],
            ["proxy_vote_application_deadline", "replacement_pack_start_date"],
        )


def clear_new_timetable_fields(apps, schema_editor):
    Election = apps.get_model("elections", "Election")
    qs = Election.private_objects.using(schema_editor.connection.alias)

    qs.update(
        proxy_vote_application_deadline=None,
        replacement_pack_start_date=None,
    )


class Migration(migrations.Migration):
    dependencies = [
        ("elections", "0092_election_replacement_pack_start_date"),
    ]

    operations = [
        migrations.RunPython(
            backfill_new_timetable_fields, clear_new_timetable_fields
        )
    ]
