# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-10 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("organisations", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="organisation",
            name="organisation_type",
            field=models.CharField(blank=True, max_length=255),
        )
    ]
