# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-10 17:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0002_organisation_organisation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='organisation_subtype',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
