# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-11 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("elections", "0004_electedrole"),
        ("organisations", "0004_auto_20161010_1802"),
    ]

    operations = [
        migrations.AddField(
            model_name="organisation",
            name="election_types",
            field=models.ManyToManyField(
                through="elections.ElectedRole", to="elections.ElectionType"
            ),
        )
    ]
