# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-11 19:18
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("organisations", "0005_organisation_election_types")]

    operations = [
        migrations.CreateModel(
            name="OrganisationDivision",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "official_identifier",
                    models.CharField(blank=True, db_index=True, max_length=255),
                ),
                ("gss", models.CharField(blank=True, max_length=20)),
                ("slug", models.CharField(blank=True, max_length=100)),
                ("division_type", models.CharField(blank=True, max_length=255)),
                (
                    "division_subtype",
                    models.CharField(blank=True, max_length=255),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organisations.Organisation",
                    ),
                ),
            ],
        )
    ]
