# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("organisations", "0006_organisationdivision")]

    operations = [
        migrations.AlterModelOptions(
            name="organisation", options={"ordering": ("official_name",)}
        ),
        migrations.AddField(
            model_name="organisation",
            name="election_name",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
