# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-24 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("organisations", "0007_auto_20161021_1609")]

    operations = [
        migrations.AddField(
            model_name="organisationdivision",
            name="name",
            field=models.CharField(blank=True, max_length=255),
        )
    ]
