# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-11 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "organisations",
            "0009_organisationdivision_division_election_sub_type",
        )
    ]

    operations = [
        migrations.AddField(
            model_name="organisationdivision",
            name="end_date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="organisationdivision",
            name="start_date",
            field=models.DateField(null=True),
        ),
    ]
