# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-11 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("organisations", "0010_auto_20170111_1355")]

    operations = [
        migrations.AddField(
            model_name="organisationdivision",
            name="seats_total",
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        )
    ]
