# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-11 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("organisations", "0013_auto_20170111_1443")]

    operations = [
        migrations.AddField(
            model_name="organisationdivisionset",
            name="short_title",
            field=models.CharField(blank=True, max_length=200),
        )
    ]
