# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-11 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("organisations", "0014_organisationdivisionset_short_title")]

    operations = [
        migrations.AddField(
            model_name="organisationdivisionset",
            name="mapit_generation_id",
            field=models.CharField(blank=True, max_length=255),
        )
    ]
