# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-11 17:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("organisations", "0015_organisationdivisionset_mapit_generation_id")
    ]

    def add_curies(apps, schema_editor):
        OrganisationDivision = apps.get_model("organisations", "OrganisationDivision")
        qs = OrganisationDivision.objects.exclude(gss="")
        for div in qs:
            div.gss = "gss:{}".format(div.gss)
            div.save()

    def do_nothing(apps, schema_editor):
        pass

    operations = [
        migrations.AlterModelOptions(
            name="organisationdivisionset", options={"ordering": ("start_date",)}
        ),
        migrations.RunPython(add_curies, do_nothing),
        migrations.RenameField("organisationdivision", "gss", "geography_curie"),
    ]
