# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-13 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0016_auto_20170111_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisationdivision',
            name='geography_curie',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='organisationdivision',
            name='seats_total',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
