# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-13 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("organisations", "0017_auto_20170113_1625")]

    operations = [
        migrations.AddField(
            model_name="organisationdivision",
            name="mapit_generation_high",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="organisationdivision",
            name="mapit_generation_low",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
