# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-18 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("organisations", "0018_auto_20170113_1738")]

    operations = [
        migrations.AlterModelOptions(
            name="organisationdivisionset",
            options={"ordering": ("-start_date",)},
        ),
        migrations.AddField(
            model_name="organisationdivisionset",
            name="consultation_url",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
