# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-10 15:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("organisations", "0023_auto_20170203_1802")]

    operations = [
        migrations.RunSQL(
            'ALTER TABLE "organisations_divisiongeography" ALTER COLUMN "geography" TYPE geometry(MULTIPOLYGON,4326) USING geography::geometry(MultiPolygon,4326);'
        )
    ]
