# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-10 15:37
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("organisations", "0023_auto_20170203_1802")]

    operations = [
        migrations.AlterField(
            model_name="divisiongeography",
            name="geography",
            field=django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
        )
    ]
