# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-01-31 14:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("organisations", "0028_auto_20171214_1331")]

    operations = [
        migrations.AlterModelOptions(
            name="organisationdivisionset",
            options={"get_latest_by": "start_date", "ordering": ("-start_date",)},
        )
    ]
