# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-30 16:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("organisations", "0029_auto_20180131_1424")]

    operations = [
        migrations.AlterUniqueTogether(
            name="organisationdivisionset",
            unique_together=set([("organisation", "end_date")]),
        )
    ]
