# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-05 09:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("organisations", "0032_auto_20180531_1000")]

    operations = [
        migrations.AlterModelOptions(
            name="organisation", options={"ordering": ("official_name", "-start_date")}
        ),
        migrations.AlterUniqueTogether(
            name="organisation",
            unique_together=set(
                [("official_identifier", "organisation_type", "end_date")]
            ),
        ),
    ]
