# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-07 09:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("organisations", "0038_copy_org_data")]

    operations = [
        migrations.AlterModelOptions(
            name="organisationgeography",
            options={"get_latest_by": "start_date", "ordering": ("-start_date",)},
        ),
        migrations.AlterUniqueTogether(
            name="organisationgeography",
            unique_together=set([("organisation", "end_date")]),
        ),
    ]
