# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-07 13:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("organisations", "0040_end_date_constraint")]

    operations = [
        migrations.RemoveField(model_name="divisiongeography", name="organisation"),
        migrations.RemoveField(model_name="organisation", name="gss"),
    ]
