# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-07 13:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("organisations", "0042_cleanup_old_geogs")]

    operations = [
        migrations.AlterField(
            model_name="divisiongeography",
            name="division",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="geography",
                to="organisations.OrganisationDivision",
            ),
        )
    ]
