# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-19 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("organisations", "0044_auto_20180619_1200")]

    operations = [
        migrations.AddField(
            model_name="organisation",
            name="legislation_url",
            field=models.CharField(blank=True, max_length=500, null=True),
        )
    ]
