# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-03 10:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("organisations", "0049_auto_20180703_1030")]

    operations = [
        migrations.RemoveField(
            model_name="organisationdivision", name="geography_curie"
        )
    ]
