# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-03 14:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("organisations", "0051_organisationdivision_temp_id")]

    operations = [
        migrations.RunSQL(
            """
            UPDATE organisations_organisationdivision
            SET temp_id=official_identifier
            WHERE LEFT(official_identifier,4) != 'gss:'
            AND LEFT(official_identifier,8) != 'unit_id:'
            AND LEFT(official_identifier,9) != 'osni_oid:';
            """
        )
    ]
