# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-05 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0052_auto_20180703_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='divisiongeography',
            name='source',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='organisationgeography',
            name='source',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
