# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-20 16:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("organisations", "0055_auto_20180720_1118")]

    operations = [
        migrations.CreateModel(
            name="DivisionProblem",
            fields=[],
            options={
                "proxy": True,
                "verbose_name_plural": "⚠️ Division Geography Problems",
                "indexes": [],
            },
            bases=("organisations.organisationdivision",),
        ),
        migrations.CreateModel(
            name="OrganisationGeographyProblem",
            fields=[],
            options={
                "proxy": True,
                "verbose_name_plural": "⚠️ Organisation Geography Problems",
                "indexes": [],
            },
            bases=("organisations.organisationgeography",),
        ),
        migrations.CreateModel(
            name="OrganisationProblem",
            fields=[],
            options={
                "proxy": True,
                "verbose_name_plural": "⚠️ Organisation Problems",
                "indexes": [],
            },
            bases=("organisations.organisation",),
        ),
    ]
