# Generated by Django 2.2.9 on 2020-01-29 18:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("organisations", "0057_remove_mapit_fields"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="organisationdivision",
            unique_together={("divisionset", "official_identifier")},
        ),
        migrations.RemoveField(
            model_name="organisationdivision",
            name="organisation",
        ),
    ]
