# Generated by Django 2.2.16 on 2020-12-18 09:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organisations", "0058_remove_division_organisation_fk"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organisation",
            name="organisation_type",
            field=models.CharField(
                choices=[
                    ("combined-authority", "combined-authority"),
                    ("sp", "sp"),
                    ("gla", "gla"),
                    ("local-authority", "local-authority"),
                    ("naw", "naw"),
                    ("senedd", "senedd"),
                    ("nia", "nia"),
                    ("parl", "parl"),
                    ("police-area", "police-area"),
                    ("sp", "sp"),
                    ("europarl", "europarl"),
                ],
                default="local-authority",
                max_length=255,
            ),
        ),
    ]
