# Generated by Django 2.2.16 on 2021-01-08 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organisations", "0059_add_sennedd_to_org_types"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organisation",
            name="organisation_type",
            field=models.CharField(
                choices=[
                    ("combined-authority", "combined-authority"),
                    ("sp", "sp"),
                    ("gla", "gla"),
                    ("local-authority", "local-authority"),
                    ("naw", "naw"),
                    ("senedd", "senedd"),
                    ("nia", "nia"),
                    ("parl", "parl"),
                    ("police-area", "police-area"),
                    ("europarl", "europarl"),
                ],
                default="local-authority",
                max_length=255,
            ),
        ),
    ]
