# Generated by Django 3.2 on 2022-08-11 15:45

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organisations", "0062_add_created_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="divisiongeography",
            name="geography",
            field=django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
        ),
    ]
