# Generated by Django 4.2.7 on 2023-12-04 17:53

import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organisations", "0065_city-of-london-rename"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganisationBoundaryReview",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("legislation_title", models.CharField(null=True)),
                ("slug", models.CharField()),
                ("consultation_url", models.URLField(null=True)),
                ("boundaries_url", models.URLField(null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("COMPLETED", "Completed"),
                            ("CURRENT", "Currently in Review"),
                        ]
                    ),
                ),
                ("latest_event", models.CharField(null=True)),
                ("legislation_url", models.URLField(null=True)),
                ("legislation_made", models.BooleanField(null=True)),
                (
                    "divisionset",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organisations.organisationdivisionset",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organisations.organisation",
                    ),
                ),
            ],
            options={
                "get_latest_by": "modified",
                "abstract": False,
            },
        ),
    ]
