# Generated by Django 4.2.6 on 2023-11-04 10:39

from django.db import migrations
from organisations.models import (
    OrganisationBoundaryReview,
    OrganisationDivisionSet,
)


def populate_boundary_reviews_model(apps, schema_editor):
    divsets_with_reviews = OrganisationDivisionSet.objects.exclude(
        consultation_url__isnull=True, legislation_url__isnull=True
    ).select_related("organisation")
    for ds in divsets_with_reviews:
        review = OrganisationBoundaryReview(
            organisation=ds.organisation,
            divisionset=ds,
            slug=ds.organisation.slug,
            consultation_url=ds.consultation_url,
            boundaries_url="",
            status="Completed Review",
            latest_event=None,
            legislation_title=ds.short_title,
            legislation_url=ds.legislation_url,
            legislation_made=True,
        )
        review.save()


def truncate_boundary_reviews_model(apps, schema_editor):
    OrganisationBoundaryReview.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("organisations", "0066_organisationboundaryreview"),
    ]

    operations = [
        migrations.RunPython(
            populate_boundary_reviews_model, truncate_boundary_reviews_model
        )
    ]
