# Generated by Django 4.2.7 on 2023-12-05 16:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organisations", "0067_populate_boundary_reviews"),
    ]

    operations = [
        migrations.AddField(
            model_name="organisationboundaryreview",
            name="effective_date",
            field=models.DateField(null=True),
        ),
    ]
