# Generated by Django 4.2.7 on 2023-12-05 16:08

from django.db import migrations
from django.db.models import OuterRef, Subquery
from organisations.models import OrganisationBoundaryReview


def populate_effective_date_field(apps, schema_editor):
    OrganisationBoundaryReview.objects.filter(divisionset__isnull=False).update(
        effective_date=Subquery(
            OrganisationBoundaryReview.objects.filter(pk=OuterRef("pk")).values(
                "divisionset__start_date"
            )[:1]
        )
    )


def set_effective_date_to_none(apps, schema_editor):
    OrganisationBoundaryReview.objects.all().update(effective_date=None)


class Migration(migrations.Migration):
    dependencies = [
        ("organisations", "0068_organisationboundaryreview_effective_date"),
    ]

    operations = [
        migrations.RunPython(
            populate_effective_date_field, set_effective_date_to_none
        )
    ]
