# Generated by Django 4.2.7 on 2023-12-12 09:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organisations", "0069_populate_obr_effective_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="organisationboundaryreview",
            name="edit_status",
            field=models.CharField(
                choices=[("UNLOCKED", "Unlocked"), ("LOCKED", "Locked")],
                default="UNLOCKED",
            ),
        ),
    ]
