# Generated by Django 4.2.7 on 2023-12-20 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organisations", "0070_organisationboundaryreview_edit_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organisationboundaryreview",
            name="boundaries_url",
            field=models.CharField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="organisationboundaryreview",
            name="consultation_url",
            field=models.URLField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="organisationboundaryreview",
            name="divisionset",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="organisations.organisationdivisionset",
            ),
        ),
        migrations.AlterField(
            model_name="organisationboundaryreview",
            name="effective_date",
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="organisationboundaryreview",
            name="latest_event",
            field=models.CharField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="organisationboundaryreview",
            name="legislation_made",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="organisationboundaryreview",
            name="legislation_title",
            field=models.CharField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="organisationboundaryreview",
            name="legislation_url",
            field=models.URLField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="organisationboundaryreview",
            name="organisation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="organisations.organisation",
            ),
        ),
    ]
