# Generated by Django 4.2.17 on 2024-12-16 13:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "organisations",
            "0071_alter_organisationboundaryreview_boundaries_url_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="organisationdivision",
            name="territory_code",
            field=models.CharField(
                choices=[
                    ("ENG", "England"),
                    ("NIR", "Northern Ireland"),
                    ("SCT", "Scotland"),
                    ("WLS", "Wales"),
                ],
                max_length=10,
                verbose_name="Territory",
            ),
        ),
    ]
