# Generated by Django 4.2.22 on 2025-09-11 09:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organisations", "0072_alter_organisationdivision_territory_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="organisationdivisionset",
            name="pmtiles_md5_hash",
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
