# Generated by Django 5.2.15 on 2026-07-20 15:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organisations", "0073_organisationdivisionset_pmtiles_md5_hash"),
    ]

    operations = [
        migrations.AddField(
            model_name="organisationboundaryreview",
            name="public_visibility",
            field=models.CharField(
                choices=[("HIDDEN", "Hidden"), ("MAP", "Map")],
                default="HIDDEN",
            ),
        ),
    ]
