# Generated by Django 5.2.16 on 2026-08-24 12:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organisations", "0074_organisationboundaryreview_public_visibility"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organisationboundaryreview",
            name="public_visibility",
            field=models.CharField(
                choices=[
                    ("HIDDEN", "Hidden"),
                    ("CONSULTATION", "Consultation"),
                    ("MAP", "Map"),
                ],
                default="HIDDEN",
            ),
        ),
    ]
