# Generated by Django 5.2.16 on 2026-09-09 11:28

import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "organisations",
            "0075_alter_organisationboundaryreview_public_visibility",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganisationChange",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "change_type",
                    models.CharField(
                        choices=[
                            ("CREATE", "Create"),
                            ("UPDATE", "Update"),
                            ("END", "End"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "information_url",
                    models.URLField(
                        blank=True,
                        default="",
                        help_text="A link to an org-specific information resource. This field can be used in addition to, or instead of, the multi-org information url on the legislation, if the affected org has its own dedicated info resource.",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        limit_choices_to=models.Q(
                            (
                                "organisation_type__in",
                                ["police-area", "europarl"],
                            ),
                            _negated=True,
                        ),
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organisations.organisation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrganisationChangeLegislation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "provisional_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "public_visibility",
                    models.CharField(
                        choices=[
                            ("HIDDEN", "Hidden"),
                            ("INFORM", "Inform"),
                            ("MAP", "Map"),
                        ],
                        default="HIDDEN",
                    ),
                ),
                (
                    "information_url",
                    models.URLField(
                        blank=True,
                        default="",
                        help_text="A Link to a general, multi-org information resource",
                    ),
                ),
                ("explanation", models.TextField(blank=True, default="")),
                ("legislation_title", models.CharField(blank=True, default="")),
                ("legislation_url", models.URLField(blank=True, default="")),
                ("legislation_made", models.BooleanField(default=False)),
                (
                    "effective_date",
                    models.DateField(blank=True, default=None, null=True),
                ),
                (
                    "affected_organisations",
                    models.ManyToManyField(
                        blank=True,
                        through="organisations.OrganisationChange",
                        to="organisations.organisation",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Organisation Change Legislation",
                "get_latest_by": "modified",
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="organisationchange",
            name="organisation_change_legislation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="organisations.organisationchangelegislation",
            ),
        ),
        migrations.AddConstraint(
            model_name="organisationchangelegislation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("provisional_name__gt", ""),
                    ("legislation_title__gt", ""),
                    _connector="OR",
                ),
                name="provisional_name_or_legislation_title_not_blank",
            ),
        ),
        migrations.AddConstraint(
            model_name="organisationchange",
            constraint=models.UniqueConstraint(
                fields=("organisation_change_legislation", "organisation"),
                name="unique_ocl_organisation",
            ),
        ),
    ]
