# Generated by Django 5.2.16 on 2026-09-09 13:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "organisations",
            "0076_organisationchange_organisationchangelegislation_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="organisation",
            name="provisional",
            field=models.BooleanField(default=False),
        ),
    ]
