# Generated by Django 5.2.16 on 2026-09-10 18:58

import organisations.models.organisations
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("organisations", "0077_organisation_provisional"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="organisation",
            managers=[
                (
                    "private_objects",
                    organisations.models.organisations.PrivateOrganisationManager(),
                ),
            ],
        ),
    ]
